PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX mh: <https://w3id.org/ontologies-ULL/CO-META#>

SELECT DISTINCT ?metaheuristic ?class
WHERE {
  ?metaheuristic a mh:Metaheuristic .
  ?metaheuristic a ?class .
  FILTER (
    ?class != mh:Metaheuristic &&
    ?class != owl:Class &&
    ?class != owl:NamedIndividual
  )
}
ORDER BY ?metaheuristic ?class